name: start test and deploy

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    name: deploy to server
    runs-on: self-hosted
#    needs: test
    steps:
      - name: kill
        run: sudo pkill server-localhost-main -f
      - name: checkout branch
        run: cd ~/yggdrasil-api/ && git checkout deploy
      - name: git pull
        run: git pull --allow-unrelated-histories
      - name: build
        run: go build -o server-localhost-main .\src\main.go
      - name: run
        run: sudo ./server-localhost-main